package domain;
// Generated May 24, 2021 10:00:10 AM by Hibernate Tools 4.3.1



/**
 * Sinhvien generated by hbm2java
 */
public class Sinhvien  implements java.io.Serializable {


     private String mssv;
     private String tenSv;
     private float dtb;
     private String lop;

    public Sinhvien() {
    }

    public Sinhvien(String mssv, String tenSv, float dtb, String lop) {
       this.mssv = mssv;
       this.tenSv = tenSv;
       this.dtb = dtb;
       this.lop = lop;
    }
   
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getTenSv() {
        return this.tenSv;
    }
    
    public void setTenSv(String tenSv) {
        this.tenSv = tenSv;
    }
    public float getDtb() {
        return this.dtb;
    }
    
    public void setDtb(float dtb) {
        this.dtb = dtb;
    }
    public String getLop() {
        return this.lop;
    }
    
    public void setLop(String lop) {
        this.lop = lop;
    }




}


